services:
  web:
    build: .
    container_name: feuerwehr-melder
    # ports:
    #   - "8000:8000"
    volumes:
      - ./data/:/app/data/
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"                                                  #<== Enable traefik
      - "traefik.http.routers.feuerwehr-secured.rule=Host(`feuerwehr.${DOMAIN}`)"  #<== Set domain
      - "traefik.http.routers.feuerwehr-secured.entrypoints=websecure"           #<== Set entry point for HTTPS
      - "traefik.http.routers.feuerwehr-secured.tls.certresolver=mytlschallenge" #<== Set certsresolvers for https
      - "traefik.http.routers.feuerwehr-secured.middlewares=authelia"            #<== Add Authelia middlewares to protect login
      - "traefik.http.routers.feuerwehr-secured.service=feuerwehr-service"         #<== Set service
      - "traefik.http.services.feuerwehr-service.loadbalancer.server.port=8000"    #<== Set target port on container

networks:
  proxy:
    external: true